version: '2'

services:
  db:
    image: mongo:latest
    command: "--smallfiles --logpath=/dev/null"    
    volumes:
        - ./data/db:/data/db
  web:
    build: .
    working_dir: /home/cardflow
    command: npm run serve
    depends_on:
      - db
    links:
      - db
    ports:
      - "3090:3000"
    volumes:
      - ./client:/home/cardflow/client
      - ./server:/home/cardflow/server
      - ./desktop:/home/cardflow/desktop
      - ./package.json:/home/cardflow/package.json
    environment:
      MONGO_URL: mongodb://db:27017/cardflow
